import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar/Navbar";
import styles from "../styles/HomePage.module.css";
import Layout from "../components/Layout/Layout";
import MovieCard from "../components/Card/MovieCard";

// OMDB Api Key: efdc90b6
// example: http://www.omdbapi.com/?i=tt3896198&apikey=efdc90b6
// example: http://www.omdbapi.com/?t=hustle&apikey=efdc90b6

export default function HomePage() {
	const [title, setTitle] = useState("");
	const [poster, setposter] = useState("");

	useEffect(() => {
		fetch("http://www.omdbapi.com/?t=hustle&apikey=efdc90b6")
			.then((resp) => resp.json())
			.then((resp) => {
				setTitle(resp.Title);
				setposter(resp.Poster);
			});

		return () => {};
	}, []);

	return (
		<Layout>
			<div className={styles.container}>
				<Head>
					<title>fam Movies</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<header className={styles.header}>
					<Navbar />
				</header>

				<main className={styles.main}>
					<MovieCard poster={poster} title={title} />
				</main>

				<footer className={styles.footer}>
					<p>*tools: React, NextJs, Typescript</p>
				</footer>
			</div>
		</Layout>
	);
}
