import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import styles from "../styles/HomePage.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>fam Movies</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

      <header>
        <Navbar />
      </header>

			<main className={styles.main}></main>

			<footer className={styles.footer}></footer>
		</div>
	);
}
