import { useState, useEffect } from "react";
import Link from "next/link";
import styles from "../styles/HomePage.module.css";
import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import Layout from "../components/Layout/Layout";
import MovieCard from "../components/Card/MovieCard";

// OMDB Api Key: efdc90b6
// example: http://www.omdbapi.com/?i=tt3896198&apikey=efdc90b6
// example: http://www.omdbapi.com/?t=hustle&apikey=efdc90b6
// example: http://www.omdbapi.com/?s=hustle&apikey=efdc90b6

type Movie = {
	Title: string;
	Year: string;
	imdbID: string;
	Type: string;
	Poster: string;
};

export default function HomePage() {
	const [movies, setMovies] = useState<Movie[]>();
	const [error, setError] = useState("");

	useEffect(() => {
		const fetchMovies = async () => {
			const response = await fetch(
				"http://www.omdbapi.com/?s=train&apikey=efdc90b6"
			);
			const data = await response.json();

			if (data.Response === "True") {
				setMovies(data.Search);
				setError('');
			} else {
				setError(data.Error);
			}
		};

		fetchMovies();

		return () => {};
	}, []);

	return (
		<Layout>
			<div className={styles.container}>
				<Head>
					<title>fam Movies</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<header className={styles.header}>
					<Navbar />
				</header>

				<main className={styles.main}>
					<div className={styles.moviesGrid}>
						{movies ? (
							movies.map((movie, idx) => (
								<Link href={`/${movie.imdbID}`} key={idx}>
									<MovieCard
										id={movie.imdbID}
										poster={movie.Poster}
										title={movie.Title}
										year={movie.Year}
									/>
								</Link>
							))
						) : (
							<p>Searching...</p>
						)}
						{error ? <p>Error: {error}</p> : null}
					</div>
				</main>
			</div>
		</Layout>
	);
}
